name: Python Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
        django: ['4.0', '4.1']
        wagtail: ['4.1', '4.2']
        include:
          - wagtail: '4.1'
            django: '3.2'
            python: '3.7'
          - wagtail: '4.2'
            django: '3.2'
            python: '3.7'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
          tox
      env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}